version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6390"
    volumes:
      - redis_data:/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8090"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis

volumes:
  redis_data: